### ISSUE TITLE
orPrewhere() and Dialect.raw()

### ISSUE THREAD

**Issue by btimby** [mbIkola/node-clickhouse-sql#10]
I am having a really hard time trying to get the query I am looking for. I have code like this:
```javascript
  const Dialect = require('clickhouse-sql');

  const sql = Dialect;

  const q = new sql.Select();

  q
    .from('table').select('col1', 'col2', 'col3')
    .prewhere('col1', sql.EQUALS, 1)
    .prewhere('col2', sql.EQUALS, 5)
    .orPrewhere('col2', sql.EQUALS, 10);
```
Which yields:
```sql
select `col1`,`col2`,`col3` from `table`
prewhere ((`col1` = 1) and (`col2` = 5)) or (`col2` = 10) with totals
```
Note that `with totals` is present, I don't want that, but also what I really want is:
```sql
select `col1`,`col2`,`col3` from `table`
prewhere (`col1` = 1) and ((`col2` = 5) or (`col2` = 10)) with totals
```
I am not sure how to achieve this. I tried raw as well:
```javascript
  const q = new sql.Select();

  q
    .from('table').select('col1', 'col2', 'col3')
    .prewhere('col1', sql.EQUALS, 1)
    .prewhere(sql.raw('col2 = 5 OR col2 = 11'));
```
But that results in an error:
```
TypeError: Cannot convert object to primitive value
    at /app/node_modules/clickhouse-sql/dist/index.js:138:20
    at Array.map (<anonymous>)
    at Conjunction.toString (/app/node_modules/clickhouse-sql/dist/index.js:137:43)
    at Select.toString (/app/node_modules/clickhouse-sql/dist/index.js:722:63)
    at doSearchTest (/app/lib/api.js:168:12)
    at /app/lib/api.js:189:16
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by btimby** [comment]
I _think_ I fixed some things...

https://github.com/mbIkola/node-clickhouse-sql/pull/14
Allows you to use `Dialect.raw()` in `.where()` and friends. I am not sure what `.raw()` was intended for, but I think it would still work for that as well (I did not change the `Raw` class.)

https://github.com/mbIkola/node-clickhouse-sql/pull/13
This one seems pretty simple, because `request_totals` defaulted to `[]` it would always eval to true.

https://github.com/mbIkola/node-clickhouse-sql/pull/12
This is just some syntax sugar. I tried to use the abbreviations at first (but they were `undefined`). I hate typing and these are pretty "popular" abbreviations.

https://github.com/mbIkola/node-clickhouse-sql/pull/11
This one adds some IP address functions I needed.

https://github.com/mbIkola/node-clickhouse-sql/pull/15
Here I added some datetime functions I need.

**Comment by btimby** [comment]
I would still like to understand how `.orPrewhere()` and friends are intended work... IMO, you should be able to pass some conditions:

```javascript
query.orPrewhere(sql.Condition(...), sql.Condition(...))
```
And it would simply add `...and (condition1 or condition2) and...`.

I can make this happen if you like.

**Comment by mbIkola** [comment]
As far as I remember correctly - everything above is merged and released. 

> I can make this happen if you like. 
I've updated LICENSE file in this repo. Just fork and do whatever you want :)
